- hosts: all
  become: yes
  vars_files:
    - ../vars/settings.yml
  tasks:
    - name: create SCRAM (Salted Challenge Response Authentication Mechanism) user for "{{ scram_producer_user }}"
      shell: "{{ kafka_install_host_symlink }}/bin/kafka-configs.sh --zookeeper {{ inventory_hostname }}:{{ zookeeper_port }} --alter --add-config 'SCRAM-SHA-256=[iterations=8192,password={{ scram_producer_password }}]' --entity-type users --entity-name {{ scram_producer_user }}"

    - name: create SCRAM (Salted Challenge Response Authentication Mechanism) user for "{{ scram_consumer_user }}"
      shell: "{{ kafka_install_host_symlink }}/bin/kafka-configs.sh --zookeeper {{ inventory_hostname }}:{{ zookeeper_port }} --alter --add-config 'SCRAM-SHA-256=[iterations=8192,password={{ scram_consumer_password }}]' --entity-type users --entity-name {{ scram_consumer_user }}"

    - name: copy user for producer properties to config folder
      template:
        src: ../templates/zzxb.j2
        dest: "{{ kafka_install_host_symlink }}/config/zzxb.properties"
        mode: 0755
    
    - name: copy user for consumer properties to config folder
      template:
        src: ../templates/zzxb1.j2
        dest: "{{ kafka_install_host_symlink }}/config/zzxb1.properties"
        mode: 0755